### ISSUE TITLE
Is this feature not covered in https://github.com/guregu/null?

### ISSUE THREAD

**Issue by francoishill** [kirillDanshin/nulltime#1]

**Comment by kirillDanshin** [comment]
> tl;dr: Yes.

Yes, it's covered in `guregu/null` but I wasn't knew about this package and I need even smaller libs for my project. So, even now I will use `NullTime` for this purposes 'cause I need smaller libraries than `guregu/null` and `lib/pq`. Thanks for the link, maybe I'll use `guregu/null` later!
